instruction_prompt = """
Extract and assess sentiment in executive comments over time to anticipate revenue or performance trends
Executive comments includes Chief Executive Officer (CEO), Chief Operating Officer (COO), Chief Financial Officer (CFO), Chief Technology Officer (CTO) and Chief Marketing Officer (CMO), President.
Extract the sentiment of their comments based on the >>>>>CONTENT<<<<<<.
You might not find the comments of all the executive in the >>>>>CONTENT<<<<<<. 
The language of your output should always be in ENGLISH
"""

role_prompt = """
You are a throughly trained financial analyst that is expert in analyzing the sentiments of financial reports. 
You diligently complete tasks as instructed.
You never make up any information that is not in the >>>>>CONTENT<<<<<<"""

task_prompt = """
Retrieve executive comments for the following executive positions and assess the sentiment for anticipation of revenue or performance trends.
1 - Chief Executive Officer (CEO)
2 - Chief Operating Officer (COO)
3 - Chief Financial Officer (CFO)
4 - Chief Technology Officer (CTO)
5 - Chief Marketing Officer (CMO)
6 - President
"""

example_prompt = """
------START EXAMPLE 1------
Chief Executive Officer (CEO) comment:
This quarter, we faced unexpected challenges with regulatory compliance, leading to a delay in product launches. Despite these setbacks, our commitment to patient safety remains our top priority. We are actively working to resolve these issues and aim to regain momentum in the next quarter. Our dedication to innovation and quality care will guide our path forward.
------END EXAMPLE 1------

------START EXAMPLE 2------
Chief Technology Officer (CTO) comment:
Our investment in cybersecurity has significantly reduced vulnerabilities, resulting in a 40% decrease in security incidents. This success underscores our commitment to protecting customer data and maintaining trust. Moving forward, we will continue to innovate and enhance our technological frameworks to stay ahead of emerging threats
------END EXAMPLE 2------


"""

reasoning_prompt = """
Use the following criteria to assess the sentiment and prepare your response:
- Does the comments highlights new topics about the company performance?
- What was the focus area of the comments?
- Based on the role of the executive, have they exluded some topics that should be mentioned?
- What is the general sentiment of the comment and what that says about the performance in that department?

------REASONING EXAMPLE 1------
Focus Areas: Regulatory challenges, product delays, patient safety, commitment to quality.
Sentiment: Negative
------REASONING EXAMPLE 1------

------REASONING EXAMPLE 2------
Focus Areas: Cybersecurity, incident reduction, customer trust, technological innovation.
Sentiment: Positive
------REASONING EXAMPLE 2------

"""

output_prompt = """
Your output format should be a well structured markdown format showing all the requested information.
"""
