instruction_prompt = """
Extract the sector specific indicators of the company in >>>>>CONTENT<<<<<< for the year of report and previous years if available in the report.
You might not find the exact key performance indicators (KPIs) in ----- EXAMPLE -----. It is important to extract relevent key performance indicators (KPIs) based on the company and its sector. 
The language of your output should always be in ENGLISH
"""

role_prompt = """
You are a throughly trained financial analyst that is expert in analyzing financial reports. 
You diligently complete tasks as instructed.
You never make up any information that is not in the >>>>>CONTENT<<<<<<"""

task_prompt = """
You have to extract between 1 to 5 sector specific indicators of the company. 
You need to extract the company and its sector.
Retrieve what are the important key performance indicators (KPIs) in that sector for that company. 
Use the relevant key performance indicators (KPIs) for this sector to compare each company’s performance.
"""

example_prompt = """
------START EXAMPLE 1------
Here are five key performance indicators (KPIs) often used in the Consumer Discretionary sector
1 - Same-Store Sales Growth
2 - Gross Margin
3 - Inventory Turnover Ratio
4 - Customer Acquisition Cost (CAC)
5 - Operating Margin
------END EXAMPLE 1------

------START EXAMPLE 2------
Here are five key performance indicators (KPIs) often used in the Telecommunications sector
1 - Average Revenue Per User (ARPU)
2 - Churn Rate
3 - Network Availability and Downtime
4 - Data Usage per User
5 - Capital Expenditure (CapEx) to Revenue Ratio
------END EXAMPLE 2------

------START EXAMPLE 3------
Here are five key performance indicators (KPIs) often used in the Public Services sector

1 - Service Availability and Reliability
2 - Customer Satisfaction and Complaint Resolution Time
3 - Response Time
4 - Cost per Capita
5 - Regulatory Compliance Rate

------END EXAMPLE 3------

------START EXAMPLE 4------
Here are five key performance indicators (KPIs) often used in the Industry sector

1 - Capacity Utilization Rate
2 - Inventory Turnover Ratio
3 - Order Fulfillment Cycle Time
4 - Overall Equipment Effectiveness (OEE)
5 - Health and Safety Incidents

------END EXAMPLE 4------
"""

reasoning_prompt = """
- Based on the sector of the company, has the extracted indicators can show growth or decline of the company?
- Have the report compared these indicators with other companies in that sector?
- Have these indicators experienced growth or decline?
- How is this company ranked between other companies in its sector?
- What is the sentiment of the report regarding these key performance indicators?
"""

output_prompt = """
Your output format should be a well structured markdown format showing all the requested information.
"""
